version: 2
jobs: 
  build: 
    working_directory: twittler-2.0/social_graph_service
    docker: 
      - image: circleci/node:7
    steps: 
      - checkout 
      - run: npm install 
      - run: npm test 
